version: "3"

services:    
  db:
      image: postgres   
      environment:
        POSTGRES_DB: "db"
        POSTGRES_HOST_AUTH_METHOD: "trust"
      ports:
        - "5432:5432" 
  dj:
    container_name: dj
    build: django
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/code
    ports:
      - "80:80"
  ng:
    container_name: ng
    build: angular
    ports:
      - "8080:80"